### ISSUE TITLE
Feature to bypass pattern limitation.

### ISSUE THREAD

**Issue by DINNKA** [jyhsu2000/BannerMaker#18]

**Comment by DINNKA** [comment]
A way to craft banners with more than 6 patterns.

**Comment by VastayanWings** [comment]
as far as im aware this feature is already in the plugin since ages

**Comment by DINNKA** [comment]
oh sry, but how can I enable this for banner crafting?

**Comment by VastayanWings** [comment]
its only possible via the gui itself, crafting it ingame is not. not sure if this is api/vanilla related issue or just implemented by the dev. it is possible with the gui crafting of the plugin sao u cna connect it to an economy and charge users for crafting via gui

**Comment by DINNKA** [comment]
I want to add the ability to craft using player materials through the gui without limitation.

**Comment by jyhsu2000** [comment]
As I know, this limitation of banner crafting is from the client of vanilla Minecraft.
Unfortunately, we can do nothing about that by developing  Spigot/Paper plugins.

Maybe there are some alternative solutions in Fabric/Forge.
Probability someone can develop client-side mods to bypass this limitation.

**Comment by DINNKA** [comment]
but i still can create 6+ pattern banners with op via gui

**Comment by jyhsu2000** [comment]
> but i still can create 6+ pattern banners with op via gui

Sure, that is already one of the features provided by this plugin.
But it can only be done by GUI interaction.
You cannot do it via crafting table due to the limitation.

If what you mean is "why OP can do it via GUI, but other players cannot"
I guess you forget to give permission node `BannerMaker.getBanner` to players using a permission plugin.
There is more information in [README.md](https://github.com/jyhsu2000/BannerMaker/blob/master/README.md) for reference.

**Comment by DINNKA** [comment]
I have already granted this permission, but it does not allow me to craft banners with a large number of patterns. It writes about the lack of resources and does not show the required amount of resources. But I can craft simple banners through the gui.

**Comment by jyhsu2000** [comment]
I think it's a different issue. It seems like a bug in your opinion.

Please open another issue, follow [the "Bug Report" template](https://github.com/jyhsu2000/BannerMaker/issues/new?assignees=&labels=&template=BugReport.md) and fill it out with details.
It'll be helpful to clarify where the problem is.
