### ISSUE TITLE
German Translation added

### ISSUE THREAD

**Issue by VastayanWings** [jyhsu2000/BannerMaker#2]
hey i added a german translation for you bannermaker. feel free to add it in a future update if you want
[de.zip](https://github.com/jyhsu2000/BannerMaker/files/275068/de.zip)

**Comment by jyhsu2000** [comment]
Thanks for translation.
I added it into the plugin.
It will be public in next release version.

If you want to get latest version.
You can visit our [Jenkins](https://ci.kid7.club/job/BannerMaker/)

**Comment by Marrarus** [comment]
im sorry but i maked an mistake. i used bannermaker 1.3.2. and i had a little mistake in the translaton. updated my bannermaker to 1.4.1 and made a new, this time 100% complete translation (and corrected the mistake)
i also added a comment at line 13 to never change the config part of it (because it reset the translation. learned that on the hard way)
here the corrected file:
[de.zip](https://github.com/jyhsu2000/BannerMaker/files/275701/de.zip)
