### ISSUE TITLE
Cant use plugin to bypass crafting limitation on banner pattern count

### ISSUE THREAD

**Issue by Happyrobot33** [jyhsu2000/BannerMaker#21]
### Environment
- OS: Windows 10
- Server version: paper 1.20
- Minecraft version: <1.20.1
- BannerMaker version: v2.3.2 

### Expected Behaviour
- Banner Maker should allow you to fake craft using the GUI and display all of the required materials even if over banner pattern limit

### Actual Behaviour
- Banner Maker doesnt list all the required materials if the banner is over pattern count, making it impossible to bypass the vanilla limitation unless free banners is enabled

### Steps to reproduce
1. Make a banner with more than 6 patterns in the GUI
2. Try to craft it using the GUI

**Comment by jyhsu2000** [comment]
It's a designed feature, not a bug. 😅
But we can do something for enhancing this.

Let me see if I understand you correctly first.

- Banner Maker should provide a new function.
(Maybe enabled with config node or/and permission node)
- To allow players to craft complex banners (6+ patterns).
- By clicking the button in UI.
- Use required materials for crafting (if the player has no `free` permission).
- Show material estimates in UI in this situation.
But still do NOT show crafting recipe preview because it's not helpful.

Please point out if there are any items above don't fit your imagination.

**Comment by Happyrobot33** [comment]
Pretty much precisely what I'm talking about yeah :) this is the only other plugin I've found that lets you get 6+ banners, the other one is broken when they changed to the loom system, so having this as a option is huge

**Comment by jyhsu2000** [comment]
I just added a new config and permission for bypassing the 6-patterns limit.

Take a try by following the steps,
- Run the new version of BannerMaker
- Set `ComplexBannerCraft` `Enable` to `true` (Don't forget to reload the plugin or restart your server)
- Grant players `BannerMaker.getBanner.complex-craft` permission

Before the new version is being released, 
Please get the version I just finished [HERE](https://github.com/jyhsu2000/BannerMaker/suites/14498755242/artifacts/819677564), 
or you can always get the latest snapshot versions on [THIS PAGE](https://github.com/jyhsu2000/BannerMaker/actions).

**Comment by Happyrobot33** [comment]
Seems to work!
