### ISSUE TITLE
BannerMaker stop to work

### ISSUE THREAD

**Issue by Malachiel87** [jyhsu2000/BannerMaker#6]
on my 1.8.9 server with viaversion, using BM 1.4.5
i crete a letter M with pink background, after i create it,  i can't bak to menu and it trow this error:
http://pastebin.com/kvibUdkX

my language file (translated in italian) http://pastebin.com/3wKY3DXj

**Comment by jyhsu2000** [comment]
I think I need a little more information to find the reason.
Please answer the following question if you can,
- Does it only happen in PaperSpigot? Or even Spigot or other server?  
  (Because there were some special errors only happened in PaperSpigot before)
- Does it only happen with your language file? Or even default language file?
- Does it always happen when you create M with pink background? Or just once?
- Does it happen with only letter M? Only pink background? Or every letter with every background color?

**Comment by jyhsu2000** [comment]
This issue is closed because it has been inactive for a long time.
If still need a discussion of the same issue, please use issue template to create another issue.
